name: interior_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation

  rooms:
    path: ./features/rooms
  settings:
    path: ./features/settings
  profile:
    path: ./features/profile
  main:
    path: ./features/main
  dimensions:
    path: ./features/dimensions


  cupertino_icons: ^1.0.6
  auto_route_generator: ^7.3.2
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
