name: dimensions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.6
  auto_route: ^7.8.4


  rooms:
    path: ../rooms

  core_ui:
    path: ../../core_ui

  domain:
    path: ../../domain

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  auto_route_generator: ^7.3.2



flutter:
  uses-material-design: true


